### PR TITLE
add a Makefile to build C files

### PR DESCRIPTION
**Pull request by monarrk**
you mentioned in the readme you hadn't worked out a way to build the C code yet, so I made a little Makefile that'll do it. you could also add any other build steps you want to it for python; I'm not familiar with it but I think there's ways to package it and whatnot. 

it is important to note that while I'm, like, *pretty sure* this will work, I'm not on linux, so it won't actually build because I obviously don't have ALSA. so if it doesn't work, I can help try to fix it, or you can just disregard this.

### CODE REVIEW

**Comment by OwenCochell** [comment]
I'll have a look at this!

My understanding of C is still very limited, so I am still figuring out the 'correct' way to build and distribute C code. Like you said, there is a way to integrate the build process with distutils(Python's module building framework), and while I have a general idea of how to do this, I am still blurry on the details.

As of now, I am not prioritising the portability and ease of installation of this project, as it is still a huge work in progress. I want to finish up a lot of things before I 'let it loose'. In the meantime, this makefile should fill that gap just fine. I'll do some testing to make sure it plays nice with ALSA, and i'll get it merged.

Thanks!

**Comment by monarrk** [comment]
just realized a mistake, forgot to make it actually compile the object into the library, goes to show how much I know. but yeah, I know portability probably isn't a huge concern, just wanted to throw something in to help, and this happens to be something I'm experienced with. thank you for being so pleasant :)

**Comment by OwenCochell** [comment]
No worries, the details sometimes slip through the cracks.

I have done some testing and I have found a minor issue that should be easy to correct.
For some reason, the shared library files generated do work correctly unless ALSA is linked after the other parameters.

For example, this line:

```makefile
${CC} ${CFLAGS} -fPIC -c ${ALSAROOT}/midi_alsa.c -o ${ALSAROOT}/midi_alsa.o
```

Would be changed to this:

```makefile
${CC} -fPIC -c ${ALSAROOT}/midi_alsa.c -o ${ALSAROOT}/midi_alsa.o ${CFLAGS}
```

Once I move 'CFLAGS' to the end of both commands, then the compiled C code works as expected.

Why is this the case? I honestly have no idea! It is my understanding that gcc processes libraries and object files in the order they are given, so I would expect linking ALSA first would be the correct way to do things, but apparently not. I have looked into why ALSA has this oddity, but it seems no one really knows.

At any rate, moving the 'CFLAGS' variable to the end of each line should correct this weird behaviour. Relevant lines should be 12 and 15. After the change is made then I will merge this into master.

Thanks again!

**Comment by monarrk** [comment]
hm I'm not sure, that's kind of strange. the only thing I can imagine is that ALSA expects some particular symbols to be exported? but generally the link order doesn't even matter in my experience. but I mean if that fixes it, it's probably fine (??)

**Review by OwenCochell — CHANGES_REQUESTED** [review]
Move the ${CFLAGS} variable to the end of both calls to the compiler

**Comment by OwenCochell** [comment]
It is very strange. When I was first working with ALSA, I was confused as to why the compiled C code was not working, as all examples put the link before the reference to the code to be compiled. It was later when I found that it must be put after the reference to the code. Again, nobody really seems to know why this is case. Another computer oddity.

Anyways, just make the change and I will merge it in. I forgot to explicitly request a change, sorry about that. 

Thanks!

**Review by OwenCochell — APPROVED** [review]
Thanks again!

**Pull request merged**
